#pragma once
#include"../headers/selective_blur.h"
#include"../headers/fast_selective_blur.cuh"
#include"../headers/find_borders.cuh"
#include"../headers/matrix_operations.cuh"
#include"../headers/form_similarity_matrix.cuh"
#include"../headers/form_availibility_matrix.cuh"
#include"../headers/form_responsibility_matrix.cuh"
#include"../headers/form_critereon_matrix.cuh"
#include"../headers/extract_exemplars.cuh"