#pragma once
#include"../headers/selective_blur.h"
#include"../headers/fast_selective_blur.cuh"
#include"../headers/find_borders.cuh"
#include"../headers/matrix_operations.cuh"
#include"../headers/form_similarity_matrix.cuh"
#include"../headers/form_similarity_matrix_color.cuh"
#include"../headers/update_availibility_matrix.cuh"
#include"../headers/update_responsibility_matrix.cuh"
#include"../headers/update_critereon_matrix.cuh"
#include"../headers/extract_exemplars.cuh"
#include"../headers/dampen_messages.cuh"
#include"../headers/presort_matrix_ap.cuh"
#include"../headers/find_labels.cuh"
#include"../headers/update_centers.cuh"
#include"../headers/enforce_connectivity.cuh"
